name: Update Feeds
on:
    schedule:
        - cron: "0 10 * * *"
jobs:
  upload-file:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Dependencies
        run: |
            pip install requests
            pip install bs4
      - name: Webscrape
        run: python scrape/main.py
      - name: Configure Git
        run: git config --global user.email 'kevin0.0zhang@gmail.com'
      - name: Commit Feeds
        run: |
            git add feeds
            git commit -m "update feeds"
      - name: Commit Status
        run: |
            git add status.txt
            git commit -m "update status"
      - name: Push
        run: git push