name: update-rss
on:
    schedule:
        - cron: "0 10 * * *"
jobs:
  upload-file:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build dependencies
        run: |
            pip install requests
            pip install bs4
      - name: Webscrape
        run: python scrape/main.py
      - name: Add
        run: git add --all
      - name: Configure
        run: git config --global user.email 'kevin0.0zhang@gmail.com'
      - name: Commit
        run: git commit -m "update feeds"
      - name: Push
        run: git push