name: learn-github-actions
on: [push]
jobs:
  upload-file:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python main.py
      - name: Add
        run: git add output.txt