name: learn-github-actions
on: [push]
jobs:
  upload-file:
    if: "!contains(github.event.head_commit.message, 'auto')"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python main.py
      - name: Add
        run: git add output.txt
      - name: Commit
        run: git commit -m artifact-testing-auto
      - name: Push
        run: git push